server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://localhost:3100/api/prom/push

scrape_configs:
- job_name: system
  entry_parser: raw
  environment_labels:
    - label_name: 'location'
      environment_variable: 'LOCATION'
  static_configs:
  - targets:
      - localhost
    labels:
      job: tmp
      __path__: /tmp/*log
